### PR TITLE
Actor edit form

### LINKED ISSUE #57: Actors Page > Customizable fields (copy from movie edit form)

### PR DESCRIPTION
**Pull request by ho-stanley**
This PR adds:

- Edit form modal in actor page
- Message when the actor is updated

Closes #57

### CODE REVIEW

**Review by jagestedt — APPROVED** [review]
Nice! We can probably use a lot of this for the movie-page as well

**Comment by jagestedt** [comment]
what was the problem with close button btw?

**Review by LinusUnghammar — APPROVED** [review]
Looks good!

**Comment by ho-stanley** [comment]
> what was the problem with close button btw? @ho-stanley

The close button submitted the form and updated the model, even though button type was not specified to "submit".

**Pull request merged**
